---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: part-four
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/TheSamsai/devops-with-kubernetes-part-4

